services:
  db:
    image: postgres:18
    container_name: speedhawk-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresqldo

volumes:
  postgres_data: