services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./shared/certs:/shared/certs
    env_file: server/.env
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    command: npm run dev   # override prod CMD (node) with nodemon for hot reload
    volumes:
      - ./worker:/app
      - /app/node_modules
      - ./shared/certs:/shared/certs
    env_file: worker/.env
volumes:
  postgres_data: